[project]
name = "vasalytics-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "plost>=0.2.5",
    "streamlit>=1.43.2",
]

[dependency-groups]
dev = [
    "watchdog>=6.0.0",
]
